### ISSUE TITLE
Ephemeral messages not working in /holders

### ISSUE THREAD

**Issue by MarioDev666** [Million-Token-Community/million-discord-bot#49]
Despite identical code, for some reason, the Ephemeral parameter is not working in the /holders command answer from the bot.
I think it has something to do with the fact that it takes a long time to get the data, during that time, the bot says "MM Bot is thinking" in a normal non-ephemeral message, which then edits itself with the content we want, which is the holder's count. However, this leads to the message at the end with the holders count also becoming non-ephemeral.

**Comment by MarioDev666** [comment]
I would recommend using a database to store the holders counts. When a user types /holders, they get the values from the database first, while at the same time, an async operation works to get the new data and saves them to the database.
This will mean the holder's count will be a delayed by one cycle of typing the /holders command, but i see that as very minimal side effect to us having the message appear ephemeral again.

I am not sure however which is the best db library to use for this case, what are your thoughts?

**Comment by tranpeter08** [comment]
fixed
